### ISSUE TITLE
Design wireframe

### ISSUE THREAD

**Issue by felipemantovani-dev** [felipemantovani-dev/Scheduling#2]
- [x] Definir o Design wireframe
 
 https://www.figma.com/file/DiqtP7YqwHJ5pIFHOxfqj9/Scheduling-web?type=design&node-id=0%3A1&mode=design&t=sir59oTmjzL8bDFp-1
 
 @primantovani

**Comment by primantovani** [comment]
Development of a mobile wireframe (client interface).
